## Introduction To ScikitLearn(Sklearn)
1.Getting the data ready
2.choosing the right estimator/algorithm for our problem
3.Fit the model and using it for Predictions
4. Evalating the model
5. Improve the model
6. Save and load trained model

In [10]:
# Get the data ready
import pandas as pd
import numpy as np
heart_disease=pd.read_csv("heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [5]:
# Create x
x=heart_disease.drop("target", axis=1)
#create y
y=heart_disease["target"]

In [7]:
#Choose right model and hyperparameter
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [12]:
#Fit the model to training model
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2)
clf.fit(x_train, y_train);
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3
264,54,1,0,110,206,0,0,108,1,0.0,1,1,2
126,47,1,0,112,204,0,1,143,0,0.1,2,0,2
118,46,0,1,105,204,0,1,172,0,0.0,2,0,2
136,60,0,2,120,178,1,1,96,0,0.0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,43,1,0,115,303,0,1,181,0,1.2,1,0,2
86,68,1,2,118,277,0,1,151,0,1.0,2,1,3
54,63,0,2,135,252,0,0,172,0,0.0,2,0,2
63,41,1,1,135,203,0,1,132,0,0.0,1,0,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2

In [18]:
#Make prediction
clf.fit(x_train, y_train);

In [13]:
y_pred=clf.predict(x_test)
y_pred

array([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0], dtype=int64)

In [14]:
y_test

16     1
206    0
7      1
11     1
150    1
      ..
198    0
84     1
91     1
155    1
232    0
Name: target, Length: 61, dtype: int64

In [20]:
clf.score(x_train, y_train)

1.0

In [21]:
clf.score(x_test, y_test)

0.819672131147541

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.72      0.77        25
           1       0.82      0.89      0.85        36

    accuracy                           0.82        61
   macro avg       0.82      0.80      0.81        61
weighted avg       0.82      0.82      0.82        61

In [23]:
confusion_matrix(y_test, y_pred)

array([[18,  7],
       [ 4, 32]], dtype=int64)

In [24]:
accuracy_score(y_test, y_pred)

0.819672131147541

In [36]:
##Improve model
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f"Model accruacy on test set: {clf.score(x_test, y_test)*100}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 20 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 30 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 40 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 50 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 60 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 70 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 80 estimators...
Model accruacy on test set: 80.32786885245902

Trying model with 90 estimators...
Model accruacy on test set: 80.32786885245902

In [52]:
#save a model and load it
import  pickle
pickle .dump(clf, open("random_forest_model_1.pkl", "wb"))

In [55]:
loaded_model=pickle.load(open("Random_forest_model_1.pkl", "rb"))
loaded_model.score(x_test, y_test)

0.8032786885245902